<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNTMSer1\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNTMSer1/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerNTMSer1.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerNTMSer1\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerNTMSer1\App_KernelProdContainer([
    'container.build_hash' => 'NTMSer1',
    'container.build_id' => '80f462f1',
    'container.build_time' => 1709198371,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNTMSer1');
