<?php

namespace ContainerNTMSer1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Lug0zrcService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.Lug0zrc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Lug0zrc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'besoinsVitauxRepository' => ['privates', 'App\\Repository\\BesoinsVitauxRepository', 'getBesoinsVitauxRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'besoinsVitauxRepository' => 'App\\Repository\\BesoinsVitauxRepository',
            'entityManager' => '?',
        ]);
    }
}
