<?php

namespace ContainerNTMSer1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1chf6DUService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.1chf6DU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1chf6DU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'objectifRepository' => ['privates', 'App\\Repository\\ObjectifRepository', 'getObjectifRepositoryService', true],
            'planActionRepository' => ['privates', 'App\\Repository\\PlanActionRepository', 'getPlanActionRepositoryService', true],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'objectifRepository' => 'App\\Repository\\ObjectifRepository',
            'planActionRepository' => 'App\\Repository\\PlanActionRepository',
            'security' => '?',
        ]);
    }
}
