<?php

namespace ContainerNTMSer1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ThiJsvWService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.thiJsvW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.thiJsvW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'obligationFamilialeRepository' => ['privates', 'App\\Repository\\ObligationFamilialeRepository', 'getObligationFamilialeRepositoryService', true],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'obligationFamilialeRepository' => 'App\\Repository\\ObligationFamilialeRepository',
            'security' => '?',
        ]);
    }
}
