<?php

namespace ContainerNTMSer1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CMMDt_Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.cMM_Dt.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cMM_Dt.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'planActionRepository' => ['privates', 'App\\Repository\\PlanActionRepository', 'getPlanActionRepositoryService', true],
        ], [
            'entityManager' => '?',
            'planActionRepository' => 'App\\Repository\\PlanActionRepository',
        ]);
    }
}
