<?php

namespace ContainerNTMSer1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBesoinsVitauxRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\BesoinsVitauxRepository' shared autowired service.
     *
     * @return \App\Repository\BesoinsVitauxRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\BesoinsVitauxRepository'] = new \App\Repository\BesoinsVitauxRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
