<?php

namespace ContainerNTMSer1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCalendrierTelService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.UqzYhlJ.App\Entity\CalendrierTel' shared service.
     *
     * @return \App\Entity\CalendrierTel
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.UqzYhlJ": it needs an instance of "App\\Entity\\CalendrierTel" but this type has been excluded in "config/services.yaml".');
    }
}
