<?php

namespace ContainerNTMSer1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCalendrierTelTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\CalendrierTelType' shared autowired service.
     *
     * @return \App\Form\CalendrierTelType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\CalendrierTelType'] = new \App\Form\CalendrierTelType();
    }
}
