<?php

namespace ContainerNTMSer1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCalendrierEvenementService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.bacN4cq.App\Entity\CalendrierEvenement' shared service.
     *
     * @return \App\Entity\CalendrierEvenement
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.bacN4cq": it needs an instance of "App\\Entity\\CalendrierEvenement" but this type has been excluded in "config/services.yaml".');
    }
}
