<?php

namespace ContainerNTMSer1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFondUrgenceRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\FondUrgenceRepository' shared autowired service.
     *
     * @return \App\Repository\FondUrgenceRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\FondUrgenceRepository'] = new \App\Repository\FondUrgenceRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
