<?php

namespace ContainerNTMSer1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotesRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\NotesRepository' shared autowired service.
     *
     * @return \App\Repository\NotesRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\NotesRepository'] = new \App\Repository\NotesRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
