<?php

namespace ContainerNTMSer1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getObligationFamilialeTempoRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ObligationFamilialeTempoRepository' shared autowired service.
     *
     * @return \App\Repository\ObligationFamilialeTempoRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ObligationFamilialeTempoRepository'] = new \App\Repository\ObligationFamilialeTempoRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
