<?php

namespace ContainerTaTHSxT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JVcCadbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JVcCadb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JVcCadb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'mesRevenusRepository' => ['privates', 'App\\Repository\\MesRevenusRepository', 'getMesRevenusRepositoryService', true],
            'objectifFinanceLoisirRepository' => ['privates', 'App\\Repository\\ObjectifFinanceLoisirRepository', 'getObjectifFinanceLoisirRepositoryService', true],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'entityManager' => '?',
            'mesRevenusRepository' => 'App\\Repository\\MesRevenusRepository',
            'objectifFinanceLoisirRepository' => 'App\\Repository\\ObjectifFinanceLoisirRepository',
            'security' => '?',
        ]);
    }
}
