<?php

namespace ContainerTaTHSxT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UZJgVDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UZ_JgVD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UZ_JgVD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'activiteProfessionnelleRepository' => ['privates', 'App\\Repository\\ActiviteProfessionnelleRepository', 'getActiviteProfessionnelleRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'activiteProfessionnelleRepository' => 'App\\Repository\\ActiviteProfessionnelleRepository',
            'entityManager' => '?',
        ]);
    }
}
