<?php

namespace ContainerTaTHSxT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_C4v7TvsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.c4v7Tvs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.c4v7Tvs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'activiteProfessionnelleRepository' => ['privates', 'App\\Repository\\ActiviteProfessionnelleRepository', 'getActiviteProfessionnelleRepositoryService', true],
            'besoinsVitauxRepository' => ['privates', 'App\\Repository\\BesoinsVitauxRepository', 'getBesoinsVitauxRepositoryService', true],
            'mesLiensSociauxRepository' => ['privates', 'App\\Repository\\MesLiensSociauxRepository', 'getMesLiensSociauxRepositoryService', true],
            'mesLoisirsRepository' => ['privates', 'App\\Repository\\MesLoisirsRepository', 'getMesLoisirsRepositoryService', true],
            'obligationFamilialeRepository' => ['privates', 'App\\Repository\\ObligationFamilialeRepository', 'getObligationFamilialeRepositoryService', true],
            'obligationMetierRepository' => ['privates', 'App\\Repository\\ObligationMetierRepository', 'getObligationMetierRepositoryService', true],
        ], [
            'activiteProfessionnelleRepository' => 'App\\Repository\\ActiviteProfessionnelleRepository',
            'besoinsVitauxRepository' => 'App\\Repository\\BesoinsVitauxRepository',
            'mesLiensSociauxRepository' => 'App\\Repository\\MesLiensSociauxRepository',
            'mesLoisirsRepository' => 'App\\Repository\\MesLoisirsRepository',
            'obligationFamilialeRepository' => 'App\\Repository\\ObligationFamilialeRepository',
            'obligationMetierRepository' => 'App\\Repository\\ObligationMetierRepository',
        ]);
    }
}
