<?php

namespace ContainerTaTHSxT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_J7g7xbYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.J7g7xbY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.J7g7xbY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'objectifFinanceLoisirRepository' => ['privates', 'App\\Repository\\ObjectifFinanceLoisirRepository', 'getObjectifFinanceLoisirRepositoryService', true],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'entityManager' => '?',
            'objectifFinanceLoisirRepository' => 'App\\Repository\\ObjectifFinanceLoisirRepository',
            'security' => '?',
        ]);
    }
}
