<?php

namespace ContainerTaTHSxT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EFyJzxgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eFyJzxg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eFyJzxg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'besoinVitalRepasRepository' => ['privates', 'App\\Repository\\BesoinVitalRepasRepository', 'getBesoinVitalRepasRepositoryService', true],
            'besoinsVitauxRepository' => ['privates', 'App\\Repository\\BesoinsVitauxRepository', 'getBesoinsVitauxRepositoryService', true],
            'calendrierChoses' => ['privates', 'App\\Repository\\CalendrierChosesAFaireRepository', 'getCalendrierChosesAFaireRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'journalierRepository' => ['privates', 'App\\Repository\\JournalierRepository', 'getJournalierRepositoryService', true],
            'mesLiensSociauxRepository' => ['privates', 'App\\Repository\\MesLiensSociauxRepository', 'getMesLiensSociauxRepositoryService', true],
            'mesLoisirsRepository' => ['privates', 'App\\Repository\\MesLoisirsRepository', 'getMesLoisirsRepositoryService', true],
            'obligationFamilialeRepository' => ['privates', 'App\\Repository\\ObligationFamilialeRepository', 'getObligationFamilialeRepositoryService', true],
            'obligationMetierRepository' => ['privates', 'App\\Repository\\ObligationMetierRepository', 'getObligationMetierRepositoryService', true],
            'planActionRepository' => ['privates', 'App\\Repository\\PlanActionRepository', 'getPlanActionRepositoryService', true],
            'rendezVousRepository' => ['privates', 'App\\Repository\\RendezVousRepository', 'getRendezVousRepositoryService', true],
            'routineTravailRepository' => ['privates', 'App\\Repository\\RoutineTravailRepository', 'getRoutineTravailRepositoryService', true],
        ], [
            'besoinVitalRepasRepository' => 'App\\Repository\\BesoinVitalRepasRepository',
            'besoinsVitauxRepository' => 'App\\Repository\\BesoinsVitauxRepository',
            'calendrierChoses' => 'App\\Repository\\CalendrierChosesAFaireRepository',
            'entityManager' => '?',
            'journalierRepository' => 'App\\Repository\\JournalierRepository',
            'mesLiensSociauxRepository' => 'App\\Repository\\MesLiensSociauxRepository',
            'mesLoisirsRepository' => 'App\\Repository\\MesLoisirsRepository',
            'obligationFamilialeRepository' => 'App\\Repository\\ObligationFamilialeRepository',
            'obligationMetierRepository' => 'App\\Repository\\ObligationMetierRepository',
            'planActionRepository' => 'App\\Repository\\PlanActionRepository',
            'rendezVousRepository' => 'App\\Repository\\RendezVousRepository',
            'routineTravailRepository' => 'App\\Repository\\RoutineTravailRepository',
        ]);
    }
}
