<?php

namespace ContainerTaTHSxT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IoOYD8eService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ioOYD8e' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ioOYD8e'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'journalierRepository' => ['privates', 'App\\Repository\\JournalierRepository', 'getJournalierRepositoryService', true],
        ], [
            'entityManager' => '?',
            'journalierRepository' => 'App\\Repository\\JournalierRepository',
        ]);
    }
}
