<?php

namespace ContainerTaTHSxT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PKtP13pService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pKtP13p' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pKtP13p'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'taskRepository' => ['privates', 'App\\Repository\\TaskRepository', 'getTaskRepositoryService', true],
            'toDoListRepository' => ['privates', 'App\\Repository\\ToDoListRepository', 'getToDoListRepositoryService', true],
        ], [
            'entityManager' => '?',
            'taskRepository' => 'App\\Repository\\TaskRepository',
            'toDoListRepository' => 'App\\Repository\\ToDoListRepository',
        ]);
    }
}
