<?php

namespace ContainerTaTHSxT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FVeF_TService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FVeF_.t' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FVeF_.t'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'besoin_repo_repas' => ['privates', 'App\\Repository\\BesoinVitalRepasRepository', 'getBesoinVitalRepasRepositoryService', true],
            'besoinsVitauxRepository' => ['privates', 'App\\Repository\\BesoinsVitauxRepository', 'getBesoinsVitauxRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'besoin_repo_repas' => 'App\\Repository\\BesoinVitalRepasRepository',
            'besoinsVitauxRepository' => 'App\\Repository\\BesoinsVitauxRepository',
            'entityManager' => '?',
        ]);
    }
}
