<?php

namespace ContainerTaTHSxT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UqzYhlJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UqzYhlJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UqzYhlJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'calendrierTel' => ['privates', '.errored..service_locator.UqzYhlJ.App\\Entity\\CalendrierTel', NULL, 'Cannot autowire service ".service_locator.UqzYhlJ": it needs an instance of "App\\Entity\\CalendrierTel" but this type has been excluded in "config/services.yaml".'],
            'calendrierTelRepository' => ['privates', 'App\\Repository\\CalendrierTelRepository', 'getCalendrierTelRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'calendrierTel' => 'App\\Entity\\CalendrierTel',
            'calendrierTelRepository' => 'App\\Repository\\CalendrierTelRepository',
            'entityManager' => '?',
        ]);
    }
}
