<?php

namespace ContainerTaTHSxT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_C2t3ofcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.C2t3ofc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.C2t3ofc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
            'toDoListRepository' => ['privates', 'App\\Repository\\ToDoListRepository', 'getToDoListRepositoryService', true],
        ], [
            'security' => '?',
            'toDoListRepository' => 'App\\Repository\\ToDoListRepository',
        ]);
    }
}
