<?php

namespace ContainerTaTHSxT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFondUrgenceTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\FondUrgenceType' shared autowired service.
     *
     * @return \App\Form\FondUrgenceType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/FondUrgenceType.php';

        return $container->privates['App\\Form\\FondUrgenceType'] = new \App\Form\FondUrgenceType();
    }
}
