<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTaTHSxT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTaTHSxT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTaTHSxT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTaTHSxT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTaTHSxT\App_KernelDevDebugContainer([
    'container.build_hash' => 'TaTHSxT',
    'container.build_id' => '41db226e',
    'container.build_time' => 1709029055,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTaTHSxT');
