<?php

namespace ContainerVTnAict;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AgjrN6UService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AgjrN6U' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AgjrN6U'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'calendrierChosesAFaire' => ['privates', '.errored..service_locator.AgjrN6U.App\\Entity\\CalendrierChosesAFaire', NULL, 'Cannot autowire service ".service_locator.AgjrN6U": it needs an instance of "App\\Entity\\CalendrierChosesAFaire" but this type has been excluded in "config/services.yaml".'],
            'calendrierChosesAFaireRepository' => ['privates', 'App\\Repository\\CalendrierChosesAFaireRepository', 'getCalendrierChosesAFaireRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'calendrierChosesAFaire' => 'App\\Entity\\CalendrierChosesAFaire',
            'calendrierChosesAFaireRepository' => 'App\\Repository\\CalendrierChosesAFaireRepository',
            'entityManager' => '?',
        ]);
    }
}
