<?php

namespace ContainerVTnAict;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IY7kF_ZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IY7kF.Z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IY7kF.Z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'besoinVitalRepasRepository' => ['privates', 'App\\Repository\\BesoinVitalRepasRepository', 'getBesoinVitalRepasRepositoryService', true],
            'besoinsVitauxRepository' => ['privates', 'App\\Repository\\BesoinsVitauxRepository', 'getBesoinsVitauxRepositoryService', true],
            'calendrierChoses' => ['privates', 'App\\Repository\\CalendrierChosesAFaireRepository', 'getCalendrierChosesAFaireRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'journalierRepository' => ['privates', 'App\\Repository\\JournalierRepository', 'getJournalierRepositoryService', true],
            'obligationFamilialeRepository' => ['privates', 'App\\Repository\\ObligationFamilialeRepository', 'getObligationFamilialeRepositoryService', true],
            'obligationMetierRepository' => ['privates', 'App\\Repository\\ObligationMetierRepository', 'getObligationMetierRepositoryService', true],
            'routineTravailRepository' => ['privates', 'App\\Repository\\RoutineTravailRepository', 'getRoutineTravailRepositoryService', true],
        ], [
            'besoinVitalRepasRepository' => 'App\\Repository\\BesoinVitalRepasRepository',
            'besoinsVitauxRepository' => 'App\\Repository\\BesoinsVitauxRepository',
            'calendrierChoses' => 'App\\Repository\\CalendrierChosesAFaireRepository',
            'entityManager' => '?',
            'journalierRepository' => 'App\\Repository\\JournalierRepository',
            'obligationFamilialeRepository' => 'App\\Repository\\ObligationFamilialeRepository',
            'obligationMetierRepository' => 'App\\Repository\\ObligationMetierRepository',
            'routineTravailRepository' => 'App\\Repository\\RoutineTravailRepository',
        ]);
    }
}
