<?php

namespace ContainerVTnAict;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Idvo_TOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.idvo.TO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.idvo.TO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'routineTravailRepository' => ['privates', 'App\\Repository\\RoutineTravailRepository', 'getRoutineTravailRepositoryService', true],
        ], [
            'entityManager' => '?',
            'routineTravailRepository' => 'App\\Repository\\RoutineTravailRepository',
        ]);
    }
}
