<?php

namespace ContainerVTnAict;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Zwf5VZ1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zwf5VZ1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zwf5VZ1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'calendrierChosesAFaireRepository' => ['privates', 'App\\Repository\\CalendrierChosesAFaireRepository', 'getCalendrierChosesAFaireRepositoryService', true],
            'calendrierEvenementRepository' => ['privates', 'App\\Repository\\CalendrierEvenementRepository', 'getCalendrierEvenementRepositoryService', true],
            'calendrierTelRepository' => ['privates', 'App\\Repository\\CalendrierTelRepository', 'getCalendrierTelRepositoryService', true],
            'rendezVousRepository' => ['privates', 'App\\Repository\\RendezVousRepository', 'getRendezVousRepositoryService', true],
        ], [
            'calendrierChosesAFaireRepository' => 'App\\Repository\\CalendrierChosesAFaireRepository',
            'calendrierEvenementRepository' => 'App\\Repository\\CalendrierEvenementRepository',
            'calendrierTelRepository' => 'App\\Repository\\CalendrierTelRepository',
            'rendezVousRepository' => 'App\\Repository\\RendezVousRepository',
        ]);
    }
}
