<?php

namespace ContainerVTnAict;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7eRX84KService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7eRX84K' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7eRX84K'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'obligationMetierRepository' => ['privates', 'App\\Repository\\ObligationMetierRepository', 'getObligationMetierRepositoryService', true],
        ], [
            'obligationMetierRepository' => 'App\\Repository\\ObligationMetierRepository',
        ]);
    }
}
