<?php

namespace ContainerVTnAict;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BZ06eIJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BZ06eIJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BZ06eIJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'activiteProfessionnelleRepository' => ['privates', 'App\\Repository\\ActiviteProfessionnelleRepository', 'getActiviteProfessionnelleRepositoryService', true],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'activiteProfessionnelleRepository' => 'App\\Repository\\ActiviteProfessionnelleRepository',
            'security' => '?',
        ]);
    }
}
