<?php

namespace ContainerVTnAict;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCalendrierEvenementTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\CalendrierEvenementType' shared autowired service.
     *
     * @return \App\Form\CalendrierEvenementType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/CalendrierEvenementType.php';

        return $container->privates['App\\Form\\CalendrierEvenementType'] = new \App\Form\CalendrierEvenementType();
    }
}
