<?php

namespace ContainerVTnAict;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCalendrierChosesAFaireService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.AgjrN6U.App\Entity\CalendrierChosesAFaire' shared service.
     *
     * @return \App\Entity\CalendrierChosesAFaire
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.AgjrN6U": it needs an instance of "App\\Entity\\CalendrierChosesAFaire" but this type has been excluded in "config/services.yaml".');
    }
}
